spring.application.name=FlightTracker

spring.datasource.url=jdbc:postgresql://localhost:55002/flight_db
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.default_schema=flight_schema
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# @PropertySource - @Value
# @ConfigurationProperties